#!/usr/bin/env python
"""
Script to generate documentation for template variables.

This script analyzes all Jinja2 templates in the project and generates
a markdown file documenting the required context variables for each template.

Usage:
    python scripts/generate_template_docs.py [output_file]

Arguments:
    output_file: Path to the output markdown file (default: template_variables.md)
"""

import sys
import os
from pathlib import Path
from jinja2 import meta, Environment
from typing import Set

# Add the project root to the Python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))


def get_all_template_files():
    """Recursively find all template files in the templates directory"""
    template_dir = Path("templates")
    return list(template_dir.glob("**/*.html"))


def extract_template_variables(template_path: Path) -> Set[str]:
    """
    Extract all undeclared variables from a Jinja2 template.
    
    Args:
        template_path: Path to the template file
        
    Returns:
        Set of variable names used in the template
    """
    with open(template_path, 'r') as f:
        template_source = f.read()
    
    env = Environment()
    ast = env.parse(template_source)
    variables = meta.find_undeclared_variables(ast)
    return variables


def create_template_context_map():
    """
    Create a mapping of template paths to their required context variables.
    This can be used as documentation for developers.
    """
    template_files = get_all_template_files()
    context_map = {}
    
    for template_file in template_files:
        variables = extract_template_variables(template_file)
        relative_path = str(template_file.relative_to(Path("templates")))
        context_map[relative_path] = list(variables)
    
    return context_map


# Import the function from the test module
def generate_template_documentation(output_file: str = "template_variables.md"):
    """
    Generate a markdown file documenting the required variables for each template.
    
    Args:
        output_file: Path to the output markdown file
    """
    context_map = create_template_context_map()
    
    # Group templates by directory for better organization
    grouped_templates = {}
    for template_path, variables in context_map.items():
        # Get the directory path (or 'root' if in the root templates directory)
        directory = str(Path(template_path).parent)
        if directory == '.':
            directory = 'root'
            
        if directory not in grouped_templates:
            grouped_templates[directory] = []
            
        grouped_templates[directory].append((template_path, variables))
    
    # Generate the markdown content
    content = [
        "# Template Variables Documentation",
        "",
        "This file documents the required context variables for each template in the application.",
        "It is automatically generated by the test suite.",
        "",
        "## Table of Contents",
        ""
    ]
    
    # Add table of contents
    for directory in sorted(grouped_templates.keys()):
        section_name = directory.replace('/', ' > ')
        section_link = directory.replace('/', '-').lower()
        content.append(f"- [{section_name}](#{section_link})")
    
    content.append("")
    
    # Add sections for each directory
    for directory in sorted(grouped_templates.keys()):
        section_name = directory.replace('/', ' > ')
        section_id = directory.replace('/', '-').lower()
        content.append(f"## {section_name}")
        content.append("")
        
        # Sort templates within each directory
        templates_in_dir = sorted(grouped_templates[directory], key=lambda x: x[0])
        
        for template_path, variables in templates_in_dir:
            template_name = Path(template_path).name
            content.append(f"### {template_name}")
            content.append("")
            content.append(f"**Path:** `{template_path}`")
            content.append("")
            
            if variables:
                content.append("**Required Variables:**")
                content.append("")
                content.append("| Variable | Description |")
                content.append("| --- | --- |")
                
                for var in sorted(variables):
                    # Skip request as it's always required
                    if var == "request":
                        continue
                    content.append(f"| `{var}` | |")
                
                content.append("")
            else:
                content.append("**No variables required**")
                content.append("")
    
    # Write the content to the file
    with open(output_file, 'w') as f:
        f.write('\n'.join(content))
    
    return output_file


def test_generate_documentation():
    """Test that we can generate documentation for templates"""
    # Use a temporary file for testing
    output_file = "template_variables_test.md"
    
    try:
        # Generate the documentation
        generated_file = generate_template_documentation(output_file)
        
        # Check that the file exists
        assert Path(generated_file).exists(), f"Documentation file {generated_file} was not created"
        
        # Check that the file has content
        with open(generated_file, 'r') as f:
            content = f.read()
            assert "# Template Variables Documentation" in content, "Documentation file does not have expected content"
    
    finally:
        # Clean up the test file
        if Path(output_file).exists():
            Path(output_file).unlink()


def main():
    """Main entry point for the script."""
    # Get the output file from command line arguments or use default
    output_file = sys.argv[1] if len(sys.argv) > 1 else "template_variables.md"
    
    # Generate the documentation
    generated_file = generate_template_documentation(output_file)
    
    print(f"Documentation generated: {generated_file}")
    
    # Print some stats about the documentation
    with open(generated_file, 'r') as f:
        content = f.read()
        template_count = content.count("### ")
        print(f"Documented {template_count} templates")


if __name__ == "__main__":
    main() 